### ISSUE TITLE
define api package

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore#10]
# summary
instead of having the api calls from the webstore to the scientist api, we'd like to extract those calls into a package instead. this way, the package only cares about making the correct call, and receiving the correct data.

# example
- https://github.com/octokit/rest.js/

**Comment by alishaevn** [comment]
all of the api work is being done in the webstore. the functions rely on react hooks so making the api related functions into its own package would require importing react into that package. I think that's unnecessary and we can close this ticket.

before I do, @smcfarlane do you have any objection?

**Comment by smcfarlane** [comment]
I agree feel free to close
