### ISSUE TITLE
be able to accept an SOW

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#137]
ref: https://github.com/assaydepot/scientist_api_v2/issues/163

# Story
When an SOW has been submitted for a user's request, they ought to be able to select the document from their request show page. Then click the "next actions" button in the upper right corner and select "submit for approval". In doing so, an API call ought to be made that submits the chosen SOW for approval to the supplier.

# Acceptance criteria

- [ ] Users are able to approve an SOW
- [ ] The supplier is notified of the approval (this may happen automatically due to the marketplace, but we need to confirm)

# Demo

![Image](https://user-images.githubusercontent.com/29032869/213750402-87ab6aeb-6dc6-4a5f-82e1-d79da46f32f8.png)

**Comment by summer-cook** [comment]
slack thread about the process of accepting an SOW: https://assaydepot.slack.com/archives/C03FZDALABG/p1669225540056269?thread_ts=1668792169.553549&cid=C03FZDALABG

**Comment by alishaevn** [comment]
related api pr: https://github.com/assaydepot/scientist_api_v2/pull/216

**Comment by alishaevn** [comment]
blocked until #171 is merged.

**Comment by summer-cook** [comment]
endpoint: `/quote_groups/#{quote_group.id}/accept_sow.json`

**Comment by summer-cook** [comment]
Blocked due to api ticket being pushed back- proposals are hitting compliance and cannot be accepted: https://github.com/assaydepot/scientist_api_v2/issues/163#issuecomment-1442069320

**Comment by alishaevn** [comment]
chris has temporarily turned off the compliance requirement for acme-staging so that we can test this.

I'm also reaching out to sherman to create a provider specific org where the feature can be permanently turned off.
