### ISSUE TITLE
auth - create domain specific urls

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore#142]
# summary
create domain specific urls that the login flow will route to in the marketplace

**Comment by alishaevn** [comment]
this issue will be handled by the prod dev team. we are only tracking it here to remember that it needs to be done.

I reached out to sherman about it in [this slack thread](https://assaydepot.slack.com/archives/C03FZDALABG/p1675092400843159).

**Comment by alishaevn** [comment]
once the work is done by the prod dev team, we'll need to test locally that we can create a new user against a new supplier and log in. then access all the pages.

**Comment by alishaevn** [comment]
sherman informed me last week that https://assayexpress.scientist.com could be used. I verified that I was able to log in via sso and create a new user with an email/password login.
