### ISSUE TITLE
SPIKE: discuss theming tiers

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#177]
# story
during planning, we need to discuss what work would need to be done for the 3 proposed theming tiers. This will help us better understand what possible pricing options may be

**Comment by alishaevn** [comment]
# initial thoughts:

 ## tier 1
- no additional elements
- update site to USE brand colors 
- update logos
- update footer name, social media icons links and "info columns"
- updating "about us" on the home page
- update the hero image on the home page

## tier 2
- update site to place brand colors where desired
- update typography
- match their current header/footer style/layout
- featured service page

## tier 3
- add additional existing components (probably just images, titles and textboxes on the home page)
- update styling to existing components
- add additional pages

## tier 4
- creating new components? (or should this be tier 3?)
- match existing website branding
- phase 2+ asks? (e.g. delete a request)

## tier 5
- custom build (hand us a wire frame and we build it)
- extension into/of their own website

**Comment by alishaevn** [comment]
webstore - [top 10 suppliers](https://docs.google.com/spreadsheets/d/1sOQGd4kigmikdQ3KNUPoMRCu-5MF5H9x/edit#gid=1577948369)

**Comment by crisr15** [comment]
Base price needs to include: 

- new repo setup
- full hosting setup
- email server
- credentials and env files

**Comment by crisr15** [comment]
Also needs to include setup of the scientist.com client page for users to join and sign in through initially.  (Where user would create an account that link them to the supplier).

**Comment by alishaevn** [comment]
this was discussed in the client meeting on feb 16 amongst the dev and sales/marketing teams.
