### ISSUE TITLE
e2e test: requests user flow

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore#192]
# story
add cypress e2e tests

# related
EPIC: #187 

# acceptance criteria

scenarios are created for the following tests
- [ ] a user can navigate from the home page to "/requests"
  - [ ]  a signed in user sees their requests, if they have any
  - [ ]  a signed in user sees the correct "no requests" response if they don't have any requests
  - [ ]  a signed out user sees the "Unauthorized" error which asks them to sign in

- [ ] tests are passing

**Comment by summer-cook** [comment]
draft pr here
https://github.com/scientist-softserv/webstore/pull/194

**Comment by alishaevn** [comment]
closing, since this was marked as done last year.
