### ISSUE TITLE
e2e testing: setup reusable mock login/session for test environment

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore#193]
# story
when starting to create e2e tests, I realized that there are a lot of parts of the test environment such as the ability to login etc that need to be set up before properly creating the majority of them

# acceptance criteria
- [ ] be able to use a mock session to perform tests as a signed in user

# resources
cy.session
- https://docs.cypress.io/guides/end-to-end-testing/testing-your-app#Improving-performance
- https://docs.cypress.io/api/commands/session

cy.origin (need to use to login with oauth)
- https://docs.cypress.io/api/commands/origin

seeds
- https://docs.cypress.io/api/commands/task#Examples

# notes
we may test the actual nextauth/auth0 separately - this process is much more in depth. the mock login above is sufficient to allow us to perform tests on protected pages.

**Comment by alishaevn** [comment]
resource: https://next-auth.js.org/tutorials/testing-with-cypress
