### ISSUE TITLE
e2e testing: setup stubbed data for test env

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore#196]
# story
setup seeded users, wares, and requests for Cypress. 

# acceptance criteria
- [x] be able to stub a user
- [x] be able to stub all requests
- [ ] <s>be able to stub wares </s> <i> will be done as part of #251 </i>

# notes
<s>
cypress docs say there are several ways to do this:
https://learn.cypress.io/advanced-cypress-concepts/database-initialization-and-seeding

- more traditional way = creating fixtures (equivalent of factories) for all data
  - need to figure out how to configure tests to point at the fixtures and to stop the app from performing its api calls only in the test env
- possible alternate for this project = still use api (it seems like this is what is already happening by default) all data just depends on the provider ID which in the test case would just need to continue being set to a demo provider</s>

since webstore relies on api calls for its data, the preferred way to run most of these tests will be to intercept &stub out the api calls with fixtures: 
https://docs.cypress.io/api/commands/intercept

**Comment by summer-cook** [comment]
Need to ask Steven or someone knowledgable with Cypress the best way to set up the seeds / test db (see notes)

**Comment by alishaevn** [comment]
closing, as this was marked as done last year.
