### ISSUE TITLE
Flow chart & Planning for email/mailers

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore#205]
# summary
create a flow chart to visualize how the configuration for mailers in the webstore will work

# related
#135 

# acceptance
Link to flowchart: 

# notes
slack thread with meething notes:
https://assaydepot.slack.com/archives/C03FZDALABG/p1676500202848259

**Comment by summer-cook** [comment]
Here is the chart that I started:

https://lucid.app/lucidchart/4238e216-c8f8-4c94-b403-8020e82f6764/edit?view_items=8az7lfNkdKy~&invitationId=inv_f8d022db-eced-4aab-9bc8-2fa2df824580

unfortunately it wasn't until i started editing it more that it told me that i was "Out of shapes" for the document or would need to either start a free trial or upgrade 🙄 

since i didn't get very far at all it might make more sense to just switch to figma and not deal with that (unless you happen to have a lucid chart account)

**Comment by alishaevn** [comment]
clicking on the link you left took me to a screen to create a lucid chart account. since I’m going to move away from that, I don’t want to. lol. can you paste a screenshot here of what you have so far?

**Comment by summer-cook** [comment]
Yes definitely:

<img width="882" alt="image" src="https://user-images.githubusercontent.com/73361970/220936225-146aa71b-3b94-4560-b837-26ac3dcdba0a.png">

**Comment by alishaevn** [comment]
[new flow chart](https://www.figma.com/file/FyXUBZUROYIt7JZwbhbVV2/email-flow-chart?node-id=0%3A1&t=TOqiwqVMqfcVAQc5-1).

[discussion](https://assaydepot.slack.com/archives/C03FZDALABG/p1677181020026479) around the above.

**Comment by alishaevn** [comment]
we've decided on a path forward in the thread above. I will begin the work on #135.
