### ISSUE TITLE
update service images

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#28]
# story
the ware object that the api currently returns when doing a search by provider, does not return the url to a related image for that ware. I opened https://github.com/assaydepot/scientist_api_v2/issues/175 and https://github.com/assaydepot/scientist_api_v2/issues/184 against the api to update this.

be sure to confirm the images show for wares on the home, browse, featured service and request pages.

adding an alt tag to the endpoint was decided to be a maybe later feature, so we will continue rendering a hard coded alt tag.

## acceptance criteria
- [ ]  each ware references a link to an image that can be used as a thumbnail
- [ ]  ~each ware has a description of that image that can be used as the alt tag~

**Comment by alishaevn** [comment]
api tickets 175 and 184 were closed yesterday, so this work should be available for testing now. the domain will need to be updated to "acme-staging" for local testing.

**Comment by summer-cook** [comment]
<img width="1137" alt="image" src="https://user-images.githubusercontent.com/73361970/207949418-d7e66294-6c56-40d3-9fa6-0c2908e606c5.png">

the promo_image for each ware still looks like a string of the file name rather than a link that can be used. there is a property for promo_image but no promo_image_url

<img width="805" alt="image" src="https://user-images.githubusercontent.com/73361970/207949983-5116fd9c-6c30-4730-8055-d2c6f27def93.png">

I'm not sure how to create a service & add a promo image, but i feel like existing promo_images might just not have been updated and if we create more services the urls will be created correctly

**Comment by alishaevn** [comment]
turns out that `https://{{domain}}.scientist.com/api/v2/wares/:id.json` works. the promo image url is nested in the urls object. 

`https://{{domain}}.scientist.com/api/v2/providers/{{provider-id}}/wares.json` however, does not show the promo image url anywhere. 

this conversation is being had [in slack](https://assaydepot.slack.com/archives/C03FZDALABG/p1671655828060719?thread_ts=1671214895.485179&cid=C03FZDALABG).


| wares | provider |
| --- | --- |
| ![Image](https://user-images.githubusercontent.com/29032869/209173577-58a5fe2f-e8eb-4ec3-9b19-ec1a1472fcc1.png) | ![Image](https://user-images.githubusercontent.com/29032869/209173595-e0264d9e-18f0-4306-a363-cf55f09d5c7b.png) |

**Comment by alishaevn** [comment]
per today's client [meeting notes](https://docs.google.com/document/d/1_d7AV99XOdjvjIWmGBxco0hvBMofAsyeLMPRUGuLZAU/edit#), the provider endpoint will be getting updated too to return the promo image.

**Comment by alishaevn** [comment]
the above request appears to have been completed in the rx app, but I'm still not seeing it in postman. [left a comment](https://github.com/assaydepot/scientist_api_v2/issues/175#issuecomment-1372653012) on the api related ticket.

**Comment by alishaevn** [comment]
> the above request appears to have been completed in the rx app, but I'm still not seeing it in postman. [left a comment](https://github.com/assaydepot/scientist_api_v2/issues/175#issuecomment-1372653012) on the api related ticket. 

this is now working 🎉 

![Image](https://user-images.githubusercontent.com/29032869/211424871-6d158a0f-d2db-44c0-a667-42c9cd0b3af4.png)
