### ISSUE TITLE
search with query

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#29]
# story
we need to be able to conduct searches of the available supplier wares using the search bar. in #3 we connected the search bar to the api, but it can only return all items. it cannot filter according to a searched term.

there is already commented out code in the app that we should be able to use when the api is updated.

# acceptance criteria
- [ ] a non empty search returns filtered services per the search term

**Comment by alishaevn** [comment]
once https://github.com/assaydepot/scientist_api_v2/issues/158 is completed, we ought to be able to do this work.

**Comment by alishaevn** [comment]
the necessary endpoint should now be accessible for testing on staging.
re: this [slack thread](https://assaydepot.slack.com/archives/C03FZDALABG/p1671214895485179).

**Comment by summer-cook** [comment]
confirmed using staging credentials: provider w/ ID 608 has multiple ware_refs that can be searched
