### ISSUE TITLE
Phenovista Digital Storefront MVP

### ISSUE THREAD

**Issue by crisr15** [scientist-softserv/webstore#305]
# Summary

With Phenovista moving forward we want to start on a quick MVP that has their logo and some very basic branding.

**Comment by alishaevn** [comment]
related
- https://github.com/scientist-softserv/phenovista-digital-storefront/issues/1
- https://github.com/scientist-softserv/phenovista-digital-storefront/issues/2
- https://github.com/scientist-softserv/phenovista-digital-storefront/issues/5
- https://github.com/scientist-softserv/phenovista-digital-storefront/issues/8
