### ISSUE TITLE
unable to create requests

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#342]
# Story
at least as of january 9, 2024 the webstore (and phenovista) began experiencing problems creating new requests

# Acceptance Criteria
- [ ] users are able to create a new request for an identified service
- [ ] this fix is brought into the phenovista repo

# Screenshots / Video
![image](https://github.com/scientist-softserv/phenovista-digital-storefront/assets/29032869/594faf5e-23c0-444b-85e8-455c71f3c75b)

# Testing Instructions and Sample Files
- go to "/browse"
- click on "request this item" next to a service (which will require you to sign in if you haven't already)
- fill out the required fields
- press "initiate request" at the bottom right of the page

**Comment by alishaevn** [comment]
results of trying to create a new request in postman

![image](https://github.com/scientist-softserv/webstore/assets/29032869/9f32b067-c6ae-4a76-913a-5117ab53c408)

**Comment by alishaevn** [comment]
@rranauro any insight on the above error? I heard talk of changes being done with sites, but I don't know the details.

I took at look at https://github.com/assaydepot/scientist_api_v2/blob/main/spec/api/v2/quote_group_create_spec.rb#L121-L127, and what I have lines up with that spec. I would assume that since I gave the endpoint the correct data, that even if the site weren't found, it would have created it.

what am I missing?

**Comment by rranauro** [comment]
It a little hard to debug your POSTMAN without the resolution of the `{{base_url}}` and `{{new_request_id}}`

When you`POST` to the `/wares/:id/quote_groups.json` endpoint the ID is the `ware.id`. The server will generate the QuoteGroup id when it creates the entry in the database.

So, that could be one issue if the `quote_group_id` in your URL is not a valid `ware_id`.

I think the Error message you are getting is not the real issue.

I would focus here: https://github.com/assaydepot/scientist_api_v2/blob/f0648fe1ae8d006528433ac76fb13ae2ed316de6/lib/scientist_api_v2/app/controllers/scientist_api_v2/quote_groups_controller.rb#L205

Make sure the Ware is what intend. If the `quoted_ware_id` randomly matches a ware but not the one you intend then it could throw an unexpected error.

Another issue it the `organization_context`. It may be that something has changed in our Organization hierarchies and to the associated Token->User->Organization->Provider links are amiss.

These are where I would look.

**Comment by rranauro** [comment]
If you give me the domain, the ware_id, and the token you are using for the request i could log into the Server and re-trace the steps of the API and where things are failing. I'm on Support-Dev this week so this week is a good time for me to look at this in more detail,.

**Comment by alishaevn** [comment]
``` bash
base_url = https://beachsidebiotech.scientist.com/api/v2
new_request_id = 1444
```

when visiting `/wares/1444.json` in postman, it returned the expected ware.

I looked at [QuoteGroupsController#new](https://github.com/assaydepot/scientist_api_v2/blob/f0648fe1ae8d006528433ac76fb13ae2ed316de6/lib/scientist_api_v2/app/controllers/scientist_api_v2/quote_groups_controller.rb#L205) yesterday, but I wasn't getting the raised error so I assumed the ware was found. I can take a closer look today though.

I'm also not too familiar with the inner workings of `organization_context`. I'll try to find out more about that.

**Comment by alishaevn** [comment]
this issue is also being discussed in this [slack thread](https://assaydepot.slack.com/archives/CF6490Y80/p1704996805983419).
