### ISSUE TITLE
User receiving unauthorized when clicking on a service

### ISSUE THREAD

**Issue by summer-cook** [scientist-softserv/webstore#351]
When clicking this link...

![Image](https://github.com/scientist-softserv/webstore/assets/11359350/98c0fdf1-b38a-42be-8e06-9d3e56c2d7bc)

I get this view: 

![Image](https://github.com/scientist-softserv/webstore/assets/11359350/7f6abaa3-53b6-4703-9025-8f5fceeb15b3)

**Comment by alishaevn** [comment]
closed in favor of #345.
