### ISSUE TITLE
view a single request page

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#49]
# story
using the components from the component library, build out the individual request page per the images below. there are 4 phases of a request, each listed below. the page won't change too much from page to page, but good to know

# acceptance criteria

- [x] the statusbar shows on the page and shows the appropriate status
- [x] the correct identifier and request name show on the page
- [x] the correct request description shows on page
- [x] the correct documents, and document status, show on page per the request stages
- [x] the correct stats show on page
- [x] the ability to send messages
- [ ] ability to show messages

# demo
<details>
<summary> supplier review</summary>

![Image](https://user-images.githubusercontent.com/29032869/204397653-4f21fb26-e319-412e-9017-9639c3d0fe02.png)
</details>

<details>
<summary>sow selection</summary>

![Image](https://user-images.githubusercontent.com/29032869/204397852-c1d04fcc-3808-4e55-a34c-c1d87732045e.png)
</details>

<details>
<summary> work started</summary>

![Image](https://user-images.githubusercontent.com/29032869/204397915-d6d26393-c577-42cb-8417-bb641aaedbb1.png)
</details>

<details>
<summary> work completed</summary>

![Image](https://user-images.githubusercontent.com/29032869/204398027-cde169bf-8c34-40ff-899a-a6a0551df1a3.png)
</details>

**Comment by alishaevn** [comment]
# documents
### sow

![Image](https://user-images.githubusercontent.com/29032869/208171593-c287498d-0761-4a8c-93b6-88ce1a6212e7.png)

### po

![Image](https://user-images.githubusercontent.com/29032869/208171538-7c697a17-d514-491b-bd6f-ee02996da6d1.png)

**Comment by summer-cook** [comment]
Proposal for SOWs = SOW for POs

**Comment by alishaevn** [comment]
we have the ability to show messages as of https://github.com/scientist-softserv/webstore/pull/85. however, the filtering still needs to be done. refer to https://github.com/assaydepot/scientist_api_v2/issues/167 for further details (some key points noted below)
- [updating the api could be easier than duplicating login in javascript](https://github.com/assaydepot/scientist_api_v2/issues/167#issuecomment-1358452830)
  - if we duplicate the logic, I have questions about [`changed_fields`](https://github.com/assaydepot/scientist_api_v2/issues/167#issuecomment-1360348645)
- [the marketplace is somehow filtering out the messages from the webstore](https://github.com/assaydepot/scientist_api_v2/issues/167#issuecomment-1358552566)

**Comment by alishaevn** [comment]
We’re going to create a `/quote_groups/:uuid/messages` endpoint to handle the scoping (the api ticket referenced above was updated [here](https://github.com/assaydepot/scientist_api_v2/issues/167#issuecomment-1363299328))
