### ISSUE TITLE
setup lint for ci

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore#5]
# resources
- http://playbook-staging.notch8.com/en/dev/install-pronto

**Comment by crisr15** [comment]
Removing from the devops board until Xavier finishes work on the setup to see if this gets included or not. #4

**Comment by alishaevn** [comment]
this may also get included as a ci step in the current ci setup. apart from the "build" step though hopefully.

![Image](https://user-images.githubusercontent.com/29032869/213752439-b3a7788a-4073-438b-96f9-5c21e9dcebfa.png)
