### ISSUE TITLE
EPIC: setup user auth

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#68]
# story
users need to be able to authenticate in order to create/view requests. per this [spike ticket](https://github.com/scientist-softserv/webstore/issues/78), we'll be installing the nextauth package and seeing what, if any, issues we run into

# related

- [x] #67 
- [x] #132
- [x] https://github.com/scientist-softserv/webstore-component-library/issues/128
- [x] #142

# resources
- https://next-auth.js.org/configuration/providers/oauth
- https://dev.to/ndom91/adding-authentication-to-an-existing-serverless-next-js-app-in-no-time-with-nextauth-js-192h
- refer to the "How are we handling user management?" discussion point in these [meeting notes](https://docs.google.com/document/d/1oa-87EP46rbRbwBng2S3ObCdTvicBdO0876cdjxN-Ks/edit#)

**Comment by alishaevn** [comment]
how do we want to handle hiding our client id/secret?

**Comment by alishaevn** [comment]
summer, steven and I paired on this yesterday for almost 2 hours. (re: [this thread](https://assaydepot.slack.com/archives/C045P84UZ/p1671646032902339?thread_ts=1671645668.142679&cid=C045P84UZ))

steven believes we may need to update some things with the rx app. after we paired, I was able to get past the error we had been seeing and now I get a new error. that may not mean however that stuff still doesn't need to be updated with rx in order to use NextAuth.

or we could go the manual route

**Comment by summer-cook** [comment]
For more context- we were able to get past the state check, and the new error we see is that the OAuthProfile is undefined. We are currently using an empty function as a workaround to define userProfile, but the docs say:

```
   * When using an OAuth 2 provider, the user information must be requested
   * through an additional request from the userinfo endpoint.
```

in examples for this package they use a url like `"https://example.com/oauth/userinfo"` 
- we tried to use the api endpoint for userprofile but it didn't seem to return what we needed. the 2 required properties are email & user id.

**Comment by alishaevn** [comment]
from today's meeting notes
- We think that if we can get the userinfo url right, then we may have solved our problems
- Need to test the `users/profile.json` endpoint again to check the http code

**Comment by alishaevn** [comment]
from slack:

> alishaevn
  [3 hours ago](https://assaydepot.slack.com/archives/C03FZDALABG/p1672941457220549?thread_ts=1671558781.005769&cid=C03FZDALABG)
I paired with ron about this today. the access token, code and state still seem to be found from the api, but the return to the webstore app is still somehow misconfigured.
>
> the version of the code we left off testing with is at sha `8a0a024`.
>
> ron will work at getting a demo version of nextauth working to see if he can discover where the disconnect is. otherwise, we may need to do some other changes to the rx app as [steven suggested](https://assaydepot.slack.com/archives/C045P84UZ/p1671651897488939?thread_ts=1671645668.142679&cid=C045P84UZ) or go in a new direction with oauth entirely.

**Comment by alishaevn** [comment]
ron's updates about his testing with next auth and the api can be found in slack [here](https://assaydepot.slack.com/archives/C03FZDALABG/p1673195216744159).

we will be pairing more on this tomorrow.

**Comment by alishaevn** [comment]
useful links
- https://next-auth.js.org/tutorials/securing-pages-and-api-routes
