### ISSUE TITLE
SPIKE: serverless oauth2?

### ISSUE THREAD

**Issue by alishaevn** [scientist-softserv/webstore#78]
# story
research whether there is there a way to get around using server side components with oath2? There’s a good chance there isn’t a way.

# resources
- relevant meeting notes: 
  - https://docs.google.com/document/d/1oa-87EP46rbRbwBng2S3ObCdTvicBdO0876cdjxN-Ks/edit#heading=h.3zeglegwljh
  - https://docs.google.com/document/d/1vhSRoE4phOIgXoOFMkATBSVdwfkPQ7WEcZslKCADI8k/edit#heading=h.3zeglegwljh

**Comment by summer-cook** [comment]
@alishaevn 

I found this package for oauth + next: 
https://next-auth.js.org/configuration/providers/oauth

not sure if it allows us to get around using serverside components, but either way it seems useful

**Comment by summer-cook** [comment]
also I found this:

Serverless Oauth2 + Next

https://old.alistair.blog/post/serverless-oauth

**Comment by alishaevn** [comment]
thanks summer! also leaving the next authentication documentation here as a possible solution/resource
- https://nextjs.org/docs/authentication

**Comment by alishaevn** [comment]
@smcfarlane the resources above are ones I'd like to discuss. in addition to other options/ideas you have.

**Comment by alishaevn** [comment]
[meeting notes](https://docs.google.com/document/d/1Mu5_N3u9U6rBaYk8mIbO9WUXZTRZFCii25HawkZqyHo/edit?usp=sharing) from our discussion on oauth2.

**Comment by alishaevn** [comment]
ron's comment is in response to the following bullet point
- May require rx work to enhance security so we aren't authenticating to sites we don't want to authenticate to (although Ron thinks we’re pretty good here)
![Image](https://user-images.githubusercontent.com/29032869/208449761-bbf6a0e2-f1b9-4a5c-9eb4-2a2d5258aae3.png)

![Image](https://user-images.githubusercontent.com/29032869/208449872-dcb51f09-fed7-47a3-8cba-9e6cab465885.png)

**Comment by alishaevn** [comment]
per the above comments, we will install nextauth and see if we run into any issues.
