### ISSUE TITLE
set up exception tracking

### ISSUE THREAD

**Issue by orangewolf** [scientist-softserv/webstore#8]
# acceptance criteria
- [ ] create a webstore project with the softserv sentry org
- [ ] setup the app for use with sentry

**Comment by alishaevn** [comment]
we can ask team sprint in the engineering channel for assistance on setting this up.

whether we have multiple accounts or not can be determined once we have client apps. part of this will depend on who's hosting.

**Comment by alishaevn** [comment]
currently blocked until we have a staging site. re:

**Comment by alishaevn** [comment]
this app is currently deployed to https://webstore-staging.vercel.app/ so we are unblocked

**Comment by aprilrieger** [comment]
https://scientist-inc.sentry.io/projects/webstore/getting-started/javascript-react/
https://scientist-inc.sentry.io/projects/webstore/?project=4504805305810944

**Comment by alishaevn** [comment]
next js specific instructions: https://scientist-inc.sentry.io/getting-started/webstore-nextjs/javascript-nextjs/
